version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: ${FILE_RABITMQ_HOSTNAME}
    ports:
      - "5672:5672"     # RabbitMQ broker port
      - "15672:15672"   # Management UI
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      RABBITMQ_DEFAULT_USER: ${FILE_RABITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${FILE_RABITMQ_PASS}
      
  case-service:
    build:
      context: ./case_service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      ASPNETCORE_ENVIRONMENT: ${CASE_ASPNETCORE_ENVIRONMENT}
      POSTGRES_HOST: ${CASE_POSTGRES_HOST}
      POSTGRES_PORT: ${CASE_POSTGRES_PORT}
      POSTGRES_DB: ${CASE_POSTGRES_DB}
      POSTGRES_USER: ${CASE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${CASE_POSTGRES_PASSWORD}
      RABBITMQ_HOST: ${FILE_RABITMQ_HOSTNAME}
      RABBITMQ_USER: ${FILE_RABITMQ_USER}
      RABBITMQ_PASS: ${FILE_RABITMQ_PASS}
    depends_on:
      rabbitmq:
        condition: service_healthy

  case-postgres:
    image: postgres:latest
    container_name: case_db
    restart: always
    environment:
      POSTGRES_USER: ${CASE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${CASE_POSTGRES_PASSWORD}
      POSTGRES_DB: ${CASE_POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./dbdata/case-data:/var/lib/postgresql/data
  
  pdf-service:
    build:
      context: ./pdf_service
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    environment:
      ASPNETCORE_ENVIRONMENT: ${PDF_ASPNETCORE_ENVIRONMENT}
      POSTGRES_HOST: ${PDF_POSTGRES_HOST}
      POSTGRES_PORT: ${PDF_POSTGRES_PORT}
      POSTGRES_DB: ${PDF_POSTGRES_DB}
      POSTGRES_USER: ${PDF_POSTGRES_USER}
      POSTGRES_PASSWORD: ${PDF_POSTGRES_PASSWORD}
      RABBITMQ_HOST: ${FILE_RABITMQ_HOSTNAME}
      RABBITMQ_USER: ${FILE_RABITMQ_USER}
      RABBITMQ_PASS: ${FILE_RABITMQ_PASS}
      ELASTICSEARCH_URL: http://elasticsearch:9200
    volumes:
      - ./dbdata:/dbdata
    depends_on:
      rabbitmq:
        condition: service_healthy
    
  pdf-postgres:
    image: postgres:latest
    container_name: pdf_db1
    restart: always
    environment:
      POSTGRES_USER: ${PDF_POSTGRES_USER}
      POSTGRES_PASSWORD: ${PDF_POSTGRES_PASSWORD}
      POSTGRES_DB: ${PDF_POSTGRES_DB}
    ports:
      - "5431:5432"
    volumes:
      - ./dbdata/pdf-data:/var/lib/postgresql/data
  
  search-service:
    build:
      context: ./search_service
      dockerfile: Dockerfile
    ports:
      - "8002:8000"
    environment:
      ASPNETCORE_ENVIRONMENT: ${SEARCH_ASPNETCORE_ENVIRONMENT}
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      elasticsearch:
        condition: service_healthy
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    ports:
      - "9200:9200"   # REST API port
      - "9300:9300"   # cluster communication port
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  dbdata:
  esdata:
