version: '3.9'

services:
  case-service:
    build:
      context: ./case_service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Development}
      POSTGRES_HOST: ${POSTGRES_HOST:-my_postgres}
      POSTGRES_DB: ${POSTGRES_DB:-your_db}
      POSTGRES_USER: ${POSTGRES_USER:-your_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-your_pass}
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
